[workspace]

members = [
    "contracts/reputation",
    "contracts/proposal",
    "contracts/voting",
    "contracts/governance",
    "contracts/execution",
    "logic/",
	"tests"
]

[profile.release]
lto = true