[package]
name = "logic"
version = "0.1.0"
authors = ["Yassine Amor <yassine@arcadiamgroup.com>"]
edition = "2018"

[lib]
name = "logic"
doctest = false
bench = false

[dependencies]
types = { package = "casper-types", version="0.7.6" }
